export const construction: Record<string, string> = {
    frame: 'construction/frame.png',
    steelFrame: 'construction/steel-frame.png',
    frameLess10PercentBrick: 'construction/brick-10.jpg',
    n10to33BrickVeneer: 'construction/brick-33.jpg',
    n34to66BrickVeneer: 'construction/brick-66.jpg',
    n67to11BrickVeneer: 'construction/brick-100.jpg',
    brickStoneMasonry: 'construction/brick-stone.jpg',
    frameAluminumSiding: 'construction/aluminum.jpg',
    frameVinylSiding: 'construction/vinyl.jpg',
    concreteBlock: 'construction/concrete.jpg',
    stuccoWoodframe: 'construction/stucco-over-woodframe.jpg',
    stuccoBlock: 'construction/stucco-over-block.jpg',
    logHome: 'construction/log.jpg',
    prefab: 'construction/pre-fab.jpg',
    prefabManufactured: 'construction/pre-fab-manufactured.jpg',
    prefabModular: 'construction/pre-fab-modular.png',
};
