export const exterior: Record<string, string> = {
    aluminum: "src/assets/exterior/aluminum.jpg",
    asbestos: "src/assets/exterior/asbestos.jpg",
    brickVeneer: "src/assets/exterior/brick.jpg",
    cementFiber: "src/assets/exterior/cement-fiber.jpg",
    clapboard: "src/assets/exterior/clipboard.jpg",
    concreteBlock: "src/assets/exterior/concrete-block.jpg",
    stucco: "src/assets/exterior/eifs.jpg",
    log: "src/assets/exterior/log.jpg",
    steelHardboard: "src/assets/exterior/steel.jpg",
    solidBrickOrStone: "src/assets/exterior/stone-brick.jpg",
    vinyl: "src/assets/exterior/vinyl.jpg",
    woodShingle: "src/assets/exterior/wood-shingle.jpg",
    woodBoards: "src/assets/exterior/woodboards.jpg",
    glass: "src/assets/exterior/glass.jpg",
    other: "src/assets/exterior/other.jpg",
};
