export const exterior: Record<string, string> = {
  aluminum: 'exterior/aluminum.jpg',
  asbestos: 'exterior/asbestos.jpg',
  brickVeneer: 'exterior/brick.jpg',
  cementFiber: 'exterior/cement-fiber.jpg',
  clapboard: 'exterior/clipboard.jpg',
  concreteBlock: 'exterior/concrete-block.jpg',
  stucco: 'exterior/eifs.jpg',
  log: 'exterior/log.jpg',
  steelHardboard: 'exterior/steel.jpg',
  solidBrickOrStone: 'exterior/stone-brick.jpg',
  vinyl: 'exterior/vinyl.jpg',
  woodShingle: 'exterior/wood-shingle.jpg',
  woodBoards: 'exterior/woodboards.jpg',
  glass: 'exterior/glass.jpg',
  other: 'exterior/other.jpg',
}
