export const extras: Record<string, string> = {
    none: "src/assets/icons/nothing.png",
    hasBurglarAlarmSystem: "src/assets/extras/burg-alarm.png",
    deadbolts: "src/assets/extras/deadbolts.png",
    hasDeck: "src/assets/extras/deck.png",
    hasFireAlarmSystem: "src/assets/extras/fire-alarm.png",
    hasFireExtinguisher: "src/assets/extras/fire-exting.png",
    hasSprinklerSystem: "src/assets/extras/fire-sprink.png",
    hailResistantRoof: "src/assets/extras/hail-resistant-roofing.png",
    hasSwimmingPool: "src/assets/extras/pool.png",
    hasSmokeDetector: "src/assets/extras/smoke-detec.png",
    hasCODetector: "src/assets/extras/smoke-detec.png",
    smokerFree: "src/assets/extras/smoke.png",
    stormShutters: "src/assets/extras/storm-shutters.png",
    sumpPump: "src/assets/extras/sump-pump.png",
    trampoline: "src/assets/extras/trampoline.png",
    impactGlass: "src/assets/extras/impact-glass.png",
    hasScreenEnclosure: "src/assets/extras/screened-enclosure.png",
    hasCoDetector: "src/assets/extras/co-detector.png",
    doorman: "src/assets/extras/doorman.png",
    barsOnWindowsDoors: "src/assets/extras/bars.png",
};
