export const extras: Record<string, string> = {
    none: 'icons/nothing.png',
    hasBurglarAlarmSystem: 'extras/burg-alarm.png',
    deadbolts: 'extras/deadbolts.png',
    hasDeck: 'extras/deck.png',
    hasFireAlarmSystem: 'extras/fire-alarm.png',
    hasFireExtinguisher: 'extras/fire-exting.png',
    hasSprinklerSystem: 'extras/fire-sprink.png',
    hailResistantRoof: 'extras/hail-resistant-roofing.png',
    hasSwimmingPool: 'extras/pool.png',
    hasSmokeDetector: 'extras/smoke-detec.png',
    hasCODetector: 'extras/smoke-detec.png',
    smokerFree: 'extras/smoke.png',
    stormShutters: 'extras/storm-shutters.png',
    sumpPump: 'extras/sump-pump.png',
    trampoline: 'extras/trampoline.png',
    impactGlass: 'extras/impact-glass.png',
    hasScreenEnclosure: 'extras/screened-enclosure.png',
    hasCoDetector: 'extras/co-detector.png',
    doorman: 'extras/doorman.png',
    barsOnWindowsDoors: 'extras/bars.png',
};
