export const house: Record<string, string> = {
    capeCod: "src/assets/house/cape-cod.jpg",
    colonial: "src/assets/house/colonial.png",
    contemporary: "src/assets/house/contemporary.jpg",
    cottage: "src/assets/house/cottage.png",
    craftsman: "src/assets/house/craftsman.png",
    duplex: "src/assets/house/duplex.jpg",
    farmhouse: "src/assets/house/farmhouse.png",
    mediterranean: "src/assets/house/mediterranean.jpg",
    openFoundation: "src/assets/house/open-foundation.jpg",
    queenAnne: "src/assets/house/queen-anne.jpg",
    ranch: "src/assets/house/ranch.jpg",
    rowHouseCenter: "src/assets/house/row-house-center.jpg",
    rowHouseEnd: "src/assets/house/row-house-end.jpg",
    southwestAdobe: "src/assets/house/southwest-adobe.jpg",
    splitLevel: "src/assets/house/split-level.jpg",
    townHouseCenter: "src/assets/house/town-house-center.jpg",
    townHouseEnd: "src/assets/house/town-house-end.jpg",
    tudor: "src/assets/house/tudor.png",
    victorian: "src/assets/house/victorian.jpg",
};
