export const house: Record<string, string> = {
    capeCod: 'house/cape-cod.jpg',
    colonial: 'house/colonial.png',
    contemporary: 'house/contemporary.jpg',
    cottage: 'house/cottage.png',
    craftsman: 'house/craftsman.png',
    duplex: 'house/duplex.jpg',
    farmhouse: 'house/farmhouse.png',
    mediterranean: 'house/mediterranean.jpg',
    openFoundation: 'house/open-foundation.jpg',
    queenAnne: 'house/queen-anne.jpg',
    ranch: 'house/ranch.jpg',
    rowHouseCenter: 'house/row-house-center.jpg',
    rowHouseEnd: 'house/row-house-end.jpg',
    southwestAdobe: 'house/southwest-adobe.jpg',
    splitLevel: 'house/split-level.jpg',
    townHouseCenter: 'house/town-house-center.jpg',
    townHouseEnd: 'house/town-house-end.jpg',
    tudor: 'house/tudor.png',
    victorian: 'house/victorian.jpg',
};
