export const construction: Record<string, string> = {
    frame: "assets/construction/frame.png",
    steelFrame: "assets/construction/steel-frame.png",
    frameLess10PercentBrick: "assets/construction/brick-10.jpg",
    n10to33BrickVeneer: "assets/construction/brick-33.jpg",
    n34to66BrickVeneer: "assets/construction/brick-66.jpg",
    n67to11BrickVeneer: "assets/construction/brick-100.jpg",
    brickStoneMasonry: "assets/construction/brick-stone.jpg",
    frameAluminumSiding: "assets/construction/aluminum.jpg",
    frameVinylSiding: "assets/construction/vinyl.jpg",
    concreteBlock: "assets/construction/concrete.jpg",
    stuccoWoodframe: "assets/construction/stucco-over-woodframe.jpg",
    stuccoBlock: "assets/construction/stucco-over-block.jpg",
    logHome: "assets/construction/log.jpg",
    prefab: "assets/construction/pre-fab.jpg",
    prefabManufactured: "assets/construction/pre-fab-manufactured.jpg",
    prefabModular: "assets/construction/pre-fab-modular.png",
};
