export const dogs: Record<string, string> = {
    "pets-n-none": "assets/dogs/no.png",
    "pets-n-akita": "assets/dogs/akita.png",
    "pets-n-alaskanMalamute": "assets/dogs/malamute.png",
    "pets-n-cat": "assets/dogs/cat.png",
    "pets-n-chowChow": "assets/dogs/chow-chow.png",
    "pets-n-doberman": "assets/dogs/doberman.png",
    "pets-n-exoticPet": "assets/dogs/exotic.png",
    "pets-n-germanShepherd": "assets/dogs/gsheperd.png",
    "pets-n-husky": "assets/dogs/husky.png",
    "pets-n-otherBreed": "assets/dogs/other-dog-breed.png",
    "pets-n-pitBull": "assets/dogs/pitbull.png",
    "pets-n-presaCanario": "assets/dogs/canarious.png",
    "pets-n-rottweiler": "assets/dogs/rottweiler.png",
    "pets-n-staffordshireBullTerrier": "assets/dogs/staffordshire.png",
    "pets-n-wolfHybrid": "assets/dogs/wolfHybrid.png",
    "pets-n-other": "assets/dogs/other-pets.png",
};
