export const extras: Record<string, string> = {
  none: 'assets/icons/nothing.png',
  hasBurglarAlarmSystem: 'assets/extras/burg-alarm.png',
  deadbolts: 'assets/extras/deadbolts.png',
  hasDeck: 'assets/extras/deck.png',
  hasFireAlarmSystem: 'assets/extras/fire-alarm.png',
  hasFireExtinguisher: 'assets/extras/fire-exting.png',
  hasSprinklerSystem: 'assets/extras/fire-sprink.png',
  hailResistantRoof: 'assets/extras/hail-resistant-roofing.png',
  hasSwimmingPool: 'assets/extras/pool.png',
  hasSmokeDetector: 'assets/extras/smoke-detec.png',
  hasCODetector: 'assets/extras/smoke-detec.png',
  smokerFree: 'assets/extras/smoke.png',
  stormShutters: 'assets/extras/storm-shutters.png',
  sumpPump: 'assets/extras/sump-pump.png',
  trampoline: 'assets/extras/trampoline.png',
  impactGlass: 'assets/extras/impact-glass.png',
  hasScreenEnclosure: 'assets/extras/screened-enclosure.png',
  hasCoDetector: 'assets/extras/co-detector.png',
  doorman: 'assets/extras/doorman.png',
  barsOnWindowsDoors: 'assets/extras/bars.png',
}
