export const house: Record<string, string> = {
    capeCod: "assets/house/cape-cod.jpg",
    colonial: "assets/house/colonial.png",
    contemporary: "assets/house/contemporary.jpg",
    cottage: "assets/house/cottage.png",
    craftsman: "assets/house/craftsman.png",
    duplex: "assets/house/duplex.jpg",
    farmhouse: "assets/house/farmhouse.png",
    mediterranean: "assets/house/mediterranean.jpg",
    openFoundation: "assets/house/open-foundation.jpg",
    queenAnne: "assets/house/queen-anne.jpg",
    ranch: "assets/house/ranch.jpg",
    rowHouseCenter: "assets/house/row-house-center.jpg",
    rowHouseEnd: "assets/house/row-house-end.jpg",
    southwestAdobe: "assets/house/southwest-adobe.jpg",
    splitLevel: "assets/house/split-level.jpg",
    townHouseCenter: "assets/house/town-house-center.jpg",
    townHouseEnd: "assets/house/town-house-end.jpg",
    tudor: "assets/house/tudor.png",
    victorian: "assets/house/victorian.jpg",
};
